[phases.setup]
nixPkgs = ["python312", "nodejs_20", "gcc"]

[phases.build]
cmds = [
    "python src/webapp_assets_sync.py > /app/build.log 2>&1",
    "bash build_frontend.sh >> /app/build.log 2>&1",
    "pip install -r requirements.txt >> /app/build.log 2>&1"
]

[start]
cmd = "gunicorn app:app --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT"
