[phases.setup]
nixPkgs = ["python312", "nodejs_20", "gcc"]

[phases.build]
cmds = [
    "rm -rf src/webapp/dist",
    "cd src/webapp && npm install && npm run build",
    "pip install -r requirements.txt"
]

[start]
cmd = "gunicorn app:app --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT"
