[phases.setup]
nixPkgs = ["python312", "nodejs_20", "gcc"]

[phases.build]
cmds = [
    "cd src/webapp && npm install && npm run build",
    "pip install -r requirements.txt"
]

[start]
cmd = "python app.py"
